### ISSUE TITLE
Site do projeto no ghpages

### ISSUE THREAD

**Issue by gildasio** [olhoneles/politicos#18]
Opa, o que acha de colocar o site do projeto no github pages? Poderia criar um novo repositório com o nome "politicos-site" para isso e colocar a API para funcionar em um subdomínio, algo como: http://api.politicos.olhoneles.org/api/v0/political-parties/

Dessa forma, acredito, fica mais fácil de alguém poder contribuir para o projeto.

**Comment by marcelometal** [comment]
Olá @gjuniioor , não entendi porque seria mais fácil se estivesse no ghpages... O código fonte do site também é livre e é distribuido nesse repositório junto com a API. Dá uma olhada: https://github.com/olhoneles/politicos/tree/master/website

**Comment by gildasio** [comment]
Opa @marcelometal . Eu vi, mas a questão que (bem, acredito, olha se concorda) em um branch separado para o site do projeto pode ter alguns benefícios:
1. Hospedagem pronta do Github, menos custo pro servidor;
2. Preocupação com o projeto mais focada na API;
3. Possibilita de quem não saca de django mas de web possa ajudar (bem possivelmente);

Mas bem, é visão pessoal. Olha se faz sentido para mais gente.

**Comment by marcelometal** [comment]
@gjuniioor, sobre os benefícios de separar numa branch e publicar no gh-pages:
1. Hospedagem hoje não é um problema, já temos uma VM para hospedar projetos do OlhoNeles.org;
2.  Acredito que quem não quiser contribuir na API, é de boa mexer apenas na app do website;
3. Quem não saca de Django minimamente não vai conseguir contribuir, o website hoje é Django.

De toda forma, obrigado por enviar dicas.

**Comment by gildasio** [comment]
Essa dica era justamente para poder abrir o leque para quem não saca de Django, pq iria ficar num outro formato. Tranquilão! :D
